### ISSUE TITLE
Setup GitHub action to publish map-config files

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/saas-catalogs-public#1]
~**Needs discussion with @peterhassall**~

- ~Push catalog JSON files to GCS bucket~ Moved to https://github.com/TerriaJS/saas-catalogs-public/issues/13
- Push map-config files to:
  - ~GCS bucket &mdash; this requires https://github.com/TerriaJS/saas/issues/134~
  - Magda record API &mdash; this doesn't require any changes

**Comment by AnaBelgun** [comment]
@peterhassall will do GitHub Actions

**Comment by nf-s** [comment]
Related to "DE Australia - option for DEA team to update catalogue & test data services" https://github.com/TerriaJS/de-australia-map/issues/98

**Comment by peterhassall** [comment]
@nf-s to write GitHub Action to deploy map-config and catalog from GitHub repo to each SaaS Magda environment.

**Comment by nf-s** [comment]
Awaiting review from @peterhassall - and then I will add API_Key secrets to enable editing prod map-configs

**Comment by nf-s** [comment]
DOOOONE
